version: '2'
services:

    wordpress:
        image: wordpress
        ports:
            - 1337:80
        environment:
            WORDPRESS_DB_PASSWORD: sup3rs3k4t0ass

    mysql:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: sup3rs3k4t0ass
